language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit

after_script:
  - git remote show origin
  - git branch
  - git add .
  - git checkout master



matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: always
    on_failure: always